### PR TITLE
update piwik list to matomo list + encode IDN to punycode

### PR DESCRIPTION
**Pull request by ncou**

### CODE REVIEW

**Comment by oscarotero** [comment]
Hi. Thanks for this PR.
Before merge, I'd like to suggest a change, let me know what to you think.
Punycode could be an optional dependency because this functionality can be archieved using the IDN functions of php http://php.net/manual/en/ref.intl.idn.php 
So maybe we could add a `function_exists` to check if [idn_to_ascii](http://php.net/manual/en/function.idn-to-ascii.php) is available, if it doesn't, detect if punycode is installed and, otherwise throw an exception.

**Comment by ncou** [comment]
I think we can check if 'intl' module is present, to check if the idn_to_ascii function could be used.
with something like :

`if (! extension_loaded('intl')) {
    throw new RuntimeException('Intl extension is not available.');
}`

but how can we made the puny dependency optional ? is there a way in composer to install it only if intl module is not installed ? because if we install the punycode dependency it's useless to check for the intl module because the punycode->encode will do the same thing as idn_to_ascii() function.

**Comment by oscarotero** [comment]
I was thinking in adding these dependencies as suggestions (https://getcomposer.org/doc/04-schema.md#suggest) and check whether intl or punycode are installed.

**Comment by ncou** [comment]
The intl is not a dependency but a module inside PHP (you activate it via the php.ini file), and puny is a dependency.

Perhaps, i could :
1) add a warning in composer to suggest to install the puny library. 
2) and in the constructor of the middleware i do a check on the "entension_loaded" for intl AND a class_exist for trueVB\Punycode, and if both are false, i throw a runtimeexception ?

What do you think ? is that what you were thinking ?

**Comment by oscarotero** [comment]
In composer you can define php extensions as dependencies, in the same way that you can define the minimum php version required. See this example:

https://github.com/oscarotero/Embed/blob/master/composer.json#L26
this library requires not only a minimum php version, but also some extensions enabled (curl and mbstrings).

I was thinking in adding the `ext-intl` and ` trueVB\Punycode` keys in the suggestions, and then check in the constructor whether if any of these alternatives are enabled.

**Comment by ncou** [comment]
I am not really friendly with composer but it's really a great feature.
I think adding this extension could be a great check before using the middleware.

**Comment by ncou** [comment]
do you need me to do the changes ? or do you do it ?

**Comment by oscarotero** [comment]
I hoped you could do it before merging. Let me know if you prefer me to do it. I have no problem.

**Comment by ncou** [comment]
sorry i was not sure from your previous sentence, if the modifications were to be done by you or me.
I will do the changes and do a new PR. 

I will add to composer the "suggest" part for the 2 libraries. As you can see, English is not my strengths...
1)
Can you indicate/correct what the description to use in the composer json ?

`
"suggest": {
        "true/punycode": "External library to convert a Unicode encoded domain name to a IDNA ASCII form and vice-versa",
        "ext-intl": "PHP Extension to enable for converting a Unicode encoded domain name to a IDNA ASCII"
    }
`
2)
Also do you prefer to throw a runtimeException or a LogicException in the constructor if there is not at last one of the lib installed ? Personnaly i would go with the runtimeexception.
3)
I think it's not possible to simulate in phpunit a missing lib, so i was thinking to add a @codeCoverageIgnoreStart/End for the code present in the constructor. Are you ok with this ? or do you see a better way to handle this case ?

**Comment by ncou** [comment]
Hum, forget the point 1) the documentation speak about the value to be a description, but it looks more like a num version. but if you have an idear for the exception error sentence i will gladly accept :)

**Comment by oscarotero** [comment]
Don't worry, my english is not good either :)

1. I'd go with something simpler like: 
```json
"suggest": {
    "ext-intl": "To handle Unicode encoded domain name and convert to IDNA ASCII",
    "true/punycode": "As a fallback if you cannot install Intl PHP extension"
}
```

2. Yes, I think `RuntimeException` is most properly
3. Maybe, instead check whether the extension is installed, just check if the function exists? So it can be mocked with a tool like [Phony](https://github.com/eloquent/phony-phpunit/) You can see an example [here](https://github.com/middlewares/client-ip/blob/master/tests/ClientIpTest.php#L136) where the function `file_get_contents` was mocked

**Comment by ncou** [comment]
sorry for the late update.
I have add a check in the constructor throwing a runtimeexception if the 2 libs are missing.
And i have add a phpunit test using phony to check the throw.

**Comment by oscarotero** [comment]
There are still some issues in travis but I'm merging it and try to fix them.
Thanks for yor work! 👍

**Comment by ncou** [comment]
Oups sorry i didn't see. Thanks for fixing it.

**Pull request merged**
